name: vyuh_feature_developer
description: A Developer-focused feature that shows all the included features in a Vyuh-enabled App
version: 1.13.1
homepage: https://vyuh.tech
repository: https://github.com/vyuh-tech/vyuh/tree/main/packages/system/vyuh_feature_developer
issue_tracker: https://github.com/vyuh-tech/vyuh/issues

topics:
  - vyuh
  - feature
  - developer
  - system

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.1
  flutter_sticky_header: ^0.7.0
  collection: ^1.18.0
  vyuh_core: ^1.42.1
  vyuh_extension_content: ^1.23.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
