name: Deploy Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
          cache: true

      - name: Install dependencies
        run: |
          dart pub global activate melos
          dart pub get
          dart run melos bs

      - name: Make .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          envkey_UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
          envkey_UNSPLASH_SECRET_KEY: ${{ secrets.UNSPLASH_SECRET_KEY }}
          directory: apps/vyuh_demo
          file_name: .env
          fail_on_empty: false
          sort_keys: false

      - name: Build web app
        run: |
          cd apps/vyuh_demo
          flutter build web --release --base-href /

      - name: Deploy to Cloudflare Pages
        id: deployment
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy apps/vyuh_demo/build/web --project-name=vyuh
